### ISSUE TITLE
Don't push a new NuGet package version for every commit

### ISSUE THREAD

**Issue by morphx666** [morphx666/CoreAudio#10]
@uxsoft, would it be possible to set up the `dotnet.yml` so that we don't push a new NuGet package every time there's a new commit? Maybe set it up so that it needs to be run manually or perhaps when there's a new release?

**Comment by uxsoft** [comment]
Sure, you can do either. In the case of manual, you can even create a release. In both cases, the Actions could populate the binaries in the release. Which one you'd prefer?

Triggers: https://docs.github.com/en/actions/reference/events-that-trigger-workflows

Do you want to try yourself, or do you want me to raise a PR with the proposal?

**Comment by morphx666** [comment]
Thanks for the information. I'll give it a go later today.
