### ISSUE TITLE
Part to Connector and AudioVolumeLevel in Part.cs

### ISSUE THREAD

**Issue by hurbawoo** [morphx666/CoreAudio#20]
1. Part to Connector
https://learn.microsoft.com/en-us/windows/win32/coreaudio/device-topologies
I could not port the 2nd code snippet above link to c# using CoreAudio. Because **Connector** could be converted to **Part**, but **Part** could not be Converted to **Connector**. So I modified Part.cs by referencing Connector.cs as below.
```
Connector? connector;
...
public Connector? Connector
{
    get
    {
        if (connector == null)
        {
            var pUnk = Marshal.GetIUnknownForObject(part);
            var res = Marshal.QueryInterface(pUnk, ref RefIId.IIdIConnector, out var ppv);
            if (ppv != IntPtr.Zero)
                connector = new Connector((IConnector)Marshal.GetObjectForIUnknown(ppv));
            else
                connector = null;
        }
        return connector;
    }
}
```
All connectors are parts, but not all parts are connectors, so I'm not sure this way, but anyway, I needed a way to make the sample code in the official document work.

2. AudioVolumeLevel doesn't work.
I think it's because of variable overriding.
`void GetAudioVolumeLevel(AudioVolumeLevel? audioVolumeLevel) {`
I modified it as below.
```
//private AudioVolumeLevel? GetAudioVolumeLevel() {
//    return audioVolumeLevel;
//}

void GetAudioVolumeLevel() {
    part.Activate(CLSCTX.ALL, ref RefIId.IIdIAudioVolumeLevel, out var result);
    if(result is IAudioVolumeLevel level) {
        audioVolumeLevel = new AudioVolumeLevel(level);
        _AudioVolumeLevelChangeNotification = new ControlChangeNotify(this);
        Marshal.ThrowExceptionForHR(part.RegisterControlChangeCallback(ref RefIId.IIdIAudioVolumeLevel,
            _AudioVolumeLevelChangeNotification));
    }
}
```
Hopefully these will be fixed in the next version.
Thanks

**Comment by morphx666** [comment]
Thanks for your report.

Regarding issue 1) I've implemented your suggested changes and seem to be working fine - I'll need to run some more tests to be sure.

As for issue 2) I really thought this was fixed already. Anyway, `Part.cs` should only contain one definition of `GetAudioVolumeLevel`:

```csharp
private AudioVolumeLevel? GetAudioVolumeLevel() {
    if(audioVolumeLevel == null) {
        part.Activate(CLSCTX.ALL, ref RefIId.IIdIAudioVolumeLevel, out var result);
        if(result is IAudioVolumeLevel level) {
            audioVolumeLevel = new AudioVolumeLevel(level);
            _AudioVolumeLevelChangeNotification = new ControlChangeNotify(this);
            Marshal.ThrowExceptionForHR(part.RegisterControlChangeCallback(ref RefIId.IIdIAudioVolumeLevel,
                _AudioVolumeLevelChangeNotification));
        }
    }
    return audioVolumeLevel;
}
```

**Comment by hurbawoo** [comment]
@morphx666 I really appreciate it.
