### ISSUE TITLE
Add license information and debug info to csproj

### ISSUE THREAD

**Issue by LiorBanai** [morphx666/CoreAudio#21]
Hi,
This csproj has some nuget related information but no license info (and other nice to have properties).
it is good to add it so it will be shown in Visual Studio nuget management.

example:
```xml
	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryType>git</RepositoryType>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
```

**Comment by morphx666** [comment]
Thanks for the suggestion. I have updated the project file with your recommendations.

**Comment by LiorBanai** [comment]
Hi, sorry to bother you again for this but since the nuget does not include the sections
```xml
<PackageLicenseExpression>MIT</PackageLicenseExpression>
<RepositoryType>git</RepositoryType>
```

it seems auto generated tools like https://github.com/tomchavakis/nuget-license do not show correct information and do nor pull the license in the reports:
![image](https://github.com/morphx666/CoreAudio/assets/36262995/075af655-2c83-4f6a-8c9f-405712abe531)

is it possible to add those (since the license is MIT anyway).?

**Comment by LiorBanai** [comment]
example of report:
![image](https://github.com/morphx666/CoreAudio/assets/36262995/c1441989-73b3-4971-9b2d-76aba5618fd6)

**Comment by morphx666** [comment]
@uxsoft , do you think you could modify the [dotnet.yml](https://github.com/morphx666/CoreAudio/blob/master/.github/workflows/dotnet.yml) workflow so that a new `.nuspec` file is created with every new release?

For example, the `.nuspec` for the next release could look something like this:

```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
    <metadata>
        <!-- Required elements-->
        <id>xfx.CoreAudio</id>
        <version>1.28.0</version>
        <description>Windows CoreAudio wrapper for .NET</description>
        <authors>xfx</authors>

        <!-- Optional elements -->
        <projectUrl>https://github.com/morphx666/CoreAudio</<projectUrl>
	<license type="expression">MIT</license>
    </metadata>
    <!-- Optional 'files' node -->
</package>
```

**Comment by LiorBanai** [comment]
Hi, Any update on this?

**Comment by morphx666** [comment]
Hi @LiorBanai, it looks like @uxsoft never replied. I will take a closer look tomorrow and see if I can figure it out myself.

**Comment by morphx666** [comment]
@LiorBanai please upgrade to 1.35.0 and let me know what's the output of the `dotnet-project-licenses` tool.

**Comment by LiorBanai** [comment]
I think it is the same:
![image](https://github.com/morphx666/CoreAudio/assets/36262995/38bb9973-51c2-4719-bf98-d5594c42f2c6)

also on nuget. org (rigt side).

compare to other nugets (mine for example:) https://www.nuget.org/packages/Analogy.LogViewer.Interfaces

I'll check later and update

thanks for the effort :)

**Comment by morphx666** [comment]
On NuGet I can see that it now shows a link to display the [LICENSE](https://github.com/morphx666/CoreAudio/blob/master/LICENSE) file.

![image](https://github.com/morphx666/CoreAudio/assets/12353675/600a24a3-8ad7-4633-95e9-be9b04226d45)

I was hoping this would be preferable to just showing the license type.

**Comment by LiorBanai** [comment]
from my perspective, as end user, it adds a layer of complexity: having the need to navigate to a different place to see the licesne type instead of directly at a glance on the site/VS package manager / Dotnet tools. 

This will also may cause users not to use the package if they don't know immediately that it is MIT :)

with the new changes theres is now a link in the dotnet tool:

![image](https://github.com/morphx666/CoreAudio/assets/36262995/09d528a1-d1f3-471b-9962-3d7ce9fa698a)

**Comment by morphx666** [comment]
That makes sense. I will re-try the other method to just display the license type.

Wish we could have both options: display the license type as a hyperlink, like [MIT](https://github.com/morphx666/CoreAudio/blob/master/LICENSE).

**Comment by morphx666** [comment]
Version 1.37.0 seems to do the trick!

Even Package Explorer shows the correct license information:
![image](https://github.com/morphx666/CoreAudio/assets/12353675/3987889f-b578-4055-a009-4da6efc59a98)

**Comment by LiorBanai** [comment]
Indeed. Thanks a lot.
![image](https://github.com/morphx666/CoreAudio/assets/36262995/482a7f5c-8033-40be-ad6f-ab2a7b7897f0)
