### ISSUE TITLE
Feature Request: Please add IAudioPolicyConfig to access PersistedDefaultAudioEndpoints

### ISSUE THREAD

**Issue by Fragtality** [morphx666/CoreAudio#28]
First off: Thanks for your Library!
I'm using it in one of my Projects and without it one important Feature would not be possible! 😃 

While researching for another Topic on how to switch an Audio Device for an Application, I came across EarTrumpet and saw that they are using another COM-Interface from the API which exactly allows that: https://github.com/File-New-Project/EarTrumpet/blob/master/EarTrumpet/Interop/MMDeviceAPI/IAudioPolicyConfigFactoryVariantFor21H2.cs#L8

Would it be possible to add that Interface to CoreAudio?

**Comment by morphx666** [comment]
Hi @Fragtality,

That is an undocumented interface and the guys from EarTrumpet were able to implement it by reverse engineering a DLL.
https://github.com/File-New-Project/EarTrumpet/discussions/1342

But, looking at their code seems to be quite a simple implementation... perhaps you could give it a try? 😉

**Comment by Fragtality** [comment]
Yeah, really a great Discovery they made there. When researching on the Topic, it seems there was only the Solution to use some Type of Code/Dll Injection to accomplish that Goal (Audio Router, assumingly SoundVolumeView).

I'm not sure what you mean with "give it a try"? I already build a Demonstrator for the specific Problem/Discussion: https://github.com/Fragtality/BeyondAudio
I could only get that running by using the exact Code-Files from EarTrumpet because else I already failed at creating a COM-Object/Interface - so creating a Pull-Request where >90% is "wtf I'm doing here?!", is not a good Idea  😅

**Comment by morphx666** [comment]
ha ha ha... fair enough.

Let me see if I can take some time this weekend to work on this. Thankfully, EarTrumpet is under the MIT license so I don't think they'll get mad at me for _borrowing_ their code.

**Comment by Fragtality** [comment]
It is not that urgent! I just thought it would be a good Addition to the CoreAudio Library/Package since it already abstracts all the other Audio-Interfaces.

Would be nice if calls like `SetPersistedDefaultAudioEndpoint` could be so much abstracted that the Developer just has to pass the MMDevice (and Process ID, Flow and Role ofc) and the Abstraction handles the creation of the right Device-String and marshalling for COM.

**Comment by morphx666** [comment]
I have just implemented it but I don't think it's working.
Running this sample code returns 0 (`HRESULT.S_OK`) but `deviceId` is empty...

```csharp
Process[] processes = Process.GetProcessesByName("VLC");
if(processes.Length > 0) {
    IAudioPolicyConfigFactory factory = AudioPolicyConfigFactory.Create();
    int r = factory.GetPersistedDefaultAudioEndpoint(processes[0].Id, DataFlow.Render, Role.Multimedia | Role.Console, out string deviceId);
    Debugger.Break();
}
```

Can you please try it and let me know if it works for you?

**Comment by Fragtality** [comment]
I've tested it in my little App - it seems to be the intended Behavior for Applications that don't have that configured in the Windows Sound Mixer.
For an App that is configured, I get the "packed" Device-String. For an App with no Configuration (is set to use the Default Device) I also get an empty String.

**Comment by morphx666** [comment]
I can't figure out if it's working or not - no matter what I try I keep getting an empty string.

I have pushed the implementation to `master`; when you get a chance, please let me know if it works for you.
If it works, I will then implement the abstraction you mentioned to facilitate the integration with the rest of the API.

**Comment by Fragtality** [comment]
Have you tried to set a specific Device first? Either in Windows (Soundmixer Options) or with the SetPersistedDefaultAudioEndpoint Call?

**Comment by morphx666** [comment]
No, I wasn't setting it through the Sound Mixer Options - I was setting it within the app itself.
I will re-test it again later... unless you can test it first ;)

**Comment by Fragtality** [comment]
Ah, I think that is the Problem - Apps which allow to select an Output-Device will report Default in the Windows Settings (so the empty String is returned):
![image](https://github.com/user-attachments/assets/b0223a8b-1f62-4b74-80de-b0581a6d191b)


These Windows Settings (and therefore the COM Interface) are mainly useful for Apps that don't allow to select an Output-Device in the first place ;)

**Comment by Fragtality** [comment]
Here with the current master:

![image](https://github.com/user-attachments/assets/6ff03ebf-eb85-4af7-932b-2f2442a2c431)

**Comment by morphx666** [comment]
Got it. Thanks for the information and all the help.
In the latest commit you will find two new helper methods that should simplify the use of the `IAudioPolicyConfigFactory` interface:

```csharp
MMDevice? GetPersistedDefaultAudioEndpoint(MMDeviceEnumerator deviceEnumerator, int processId, DataFlow flow, Role role, DeviceState state = DeviceState.MaskAll)

void SetPersistedDefaultAudioEndpoint(int processId, DataFlow flow, Role role, MMDevice device)
```

Here's a sample on how to use them:

```csharp
IAudioPolicyConfigFactory apc = AudioPolicyConfigFactory.Create();
MMDevice device = apc.GetPersistedDefaultAudioEndpoint(devEnum, processes[0].Id, DataFlow.Render, Role.Multimedia);
```

```csharp
Process[] processes = Process.GetProcessesByName("VLC");
if(processes.Length > 0) {
    IAudioPolicyConfigFactory apc = AudioPolicyConfigFactory.Create();
    foreach(MMDevice device in devEnum.EnumerateAudioEndPoints(DataFlow.Render, DeviceState.Active)) {
        if(device.DeviceFriendlyName.Contains("Headphones")) {
            apc.SetPersistedDefaultAudioEndpoint(processes[0].Id, DataFlow.Render, Role.Multimedia, device);
            break;
        }
    }
}
```

**Comment by Fragtality** [comment]
I guess / think it is kinda working?

It is working with newest master, but only if I run my App in Debug Mode from VS. Running the App-Binary directly does not work, it just wont start. So I assume it is only me not knowing how to properly reference CoreAudio without NuGet 😅

**Comment by morphx666** [comment]
I will be updating the NuGet package later today after I have run some more tests.

**Comment by Fragtality** [comment]
Awesome!

Thanks for Time & Support 😃

**Comment by morphx666** [comment]
Thank you for suggesting this feature. I didn't even know this was even possible...

Anyway, the NuGet package has been updated. Please let me know if you encounter any issues.

**Comment by Fragtality** [comment]
Switchted to the new NuGet Package and everything works fine - Thanks!! 😃
