### ISSUE TITLE
NuGet Package?

### ISSUE THREAD

**Issue by uxsoft** [morphx666/CoreAudio#5]
Hi,
It would be useful to have this published as a NuGet package. Let me know if you want help setting up GitHub actions to auto-publish the NuGet package for every commit or something.

**Comment by morphx666** [comment]
Yes, that'd be awesome. I have never published a NuGet pkg, so if you have the know-how, please go ahead.
And just let me know if you need anything from me.

**Comment by uxsoft** [comment]
Thanks for the swift response! 

I created a pull request with the automation. When testing I created this NuGet package: https://www.nuget.org/packages/CoreAudio/

To get it working in your repository you'll need a NuGet API key set up as a secret in the GitHub repository settings. To get this API key please go to nuget.org and log in. Create the API key and specify the package name and tell me your username so I can transfer the ownership of the existing package to you.

Let me add a few screenshots for you here...

<img width="1109" alt="Screenshot 2021-08-30 at 20 05 05" src="https://user-images.githubusercontent.com/1889343/131384513-08dc5c75-e7a6-4c13-af87-fc5a05c800fd.png">
<img width="280" alt="Screenshot 2021-08-30 at 20 05 23" src="https://user-images.githubusercontent.com/1889343/131384521-8999d11a-d4f6-4956-b732-a8bf2e3b163a.png">
<img width="1261" alt="Screenshot 2021-08-30 at 20 06 32" src="https://user-images.githubusercontent.com/1889343/131384525-ef3f562b-250a-4d9d-8c16-d5015f0e0383.png">

**Comment by morphx666** [comment]
I think I was able to follow all your instructions.
My username at nuget.org is xfx
![image](https://user-images.githubusercontent.com/12353675/131391538-5b6b47e7-5434-4658-b2da-7b00d99051c2.png)

**Comment by uxsoft** [comment]
Added.

<img width="738" alt="Screenshot 2021-08-31 at 8 17 51" src="https://user-images.githubusercontent.com/1889343/131451921-3eb8c95e-321c-4212-9db6-e5bf22889870.png">

Let me raise a PR with some simple change to see if it works

**Comment by morphx666** [comment]
Thanks for your help!
